CREATE TABLE address_info (
Unique_id INT NOT NULL ,
Father_name CHAR(25) NOT NULL,
Mother_name CHAR(35) NOT NULL,
Occupation VARCHAR(10) NOT NULL,
Permanent_address VARCHAR(40),
padd_city VARCHAR(10),
padd_state VARCHAR(10),
padd_pin INT(6),
phone_no INT(12)
PRIMARY KEY (Unique_id)
) ENGINE=MyISAM
PARTITION BY RANGE (Unique_id) (
PARTITION p0 VALUES LESS THAN (500000),
PARTITION p1 VALUES LESS THAN (1000000),
PARTITION p2 VALUES LESS THAN (1500000),
PARTITION p3 VALUES LESS THAN MAXVALUE)

