CREATE TABLE personal_info (
Unique_id INT NOT NULL ,
Fname CHAR(12) NOT NULL,
Minit CHAR(12) NOT NULL,
Lname CHAR(12) NOT NULL,
Sex CHAR(1),
Date_of_birth DATE,
email VARCHAR(30)
PRIMARY KEY (Unique_id)
) ENGINE=MyISAM
PARTITION BY RANGE (Unique_id) (
PARTITION p0 VALUES LESS THAN (500000),
PARTITION p1 VALUES LESS THAN (1000000),
PARTITION p2 VALUES LESS THAN (1500000),
PARTITION p3 VALUES LESS THAN MAXVALUE)

